# Generated by Django 5.2.4 on 2025-07-09 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="alarmEvents",
            fields=[
                ("alter_id", models.AutoField(primary_key=True, serialize=False)),
                ("alter_time", models.DateTimeField(auto_now_add=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("illegal_intrusion", "非法入侵"),
                            ("deep_fake", "深度伪造"),
                            ("road_disease", "路面病害"),
                            ("abnormal_data", "异常数据"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "新建"),
                            ("PROCESSING", "处理中"),
                            ("RESOLVED", "已处理"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "related_date",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="关联日期数据"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userprofile",
                    ),
                ),
            ],
        ),
    ]
