# Generated by Django 4.2.23 on 2025-07-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0002_alter_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='roadRecord',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('road_id', models.IntegerField()),
                ('detection_time', models.DateTimeField(auto_now_add=True)),
                ('disease_type', models.IntegerField(choices=[(0, '无'), (1, '纵向裂缝'), (2, '横向裂缝'), (3, '龟裂'), (4, '坑洼'), (5, '修补')])),
                ('length', models.FloatField()),
                ('area', models.FloatField()),
                ('severity', models.IntegerField(choices=[(0, 'SAFE'), (1, 'LOW'), (2, 'MEDIUM'), (3, 'HIGH')])),
                ('path', models.CharField(max_length=255)),
                ('file_type', models.IntegerField(choices=[(0, 'VIDEO'), (1, 'IMAGE')])),
                ('description', models.JSONField(default=dict)),
                ('assigned_workers', models.ManyToManyField(blank=True, related_name='assigned_road_records', through='roadMonitor.RepairAssignment', to='web.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='repairassignment',
            name='road_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roadMonitor.roadrecord'),
        ),
        migrations.AddField(
            model_name='repairassignment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='web.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='repairassignment',
            unique_together={('road_record', 'worker')},
        ),
    ]
