# Generated by Django 5.2.4 on 2025-07-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="roadRecord",
            fields=[
                ("disease_id", models.AutoField(primary_key=True, serialize=False)),
                ("road_id", models.IntegerField()),
                ("detection_time", models.DateTimeField(auto_now_add=True)),
                (
                    "disease_type",
                    models.IntegerField(
                        choices=[
                            (1, "纵向裂缝"),
                            (2, "横向裂缝"),
                            (3, "龟裂"),
                            (4, "坑洼"),
                        ]
                    ),
                ),
                ("length", models.FloatField()),
                ("area", models.FloatField()),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(0, "SAVE"), (1, "LOW"), (2, "MEDIUM"), (3, "HIGH")]
                    ),
                ),
                ("path", models.CharField(max_length=255)),
            ],
        ),
    ]
