# Generated by Django 5.2.4 on 2025-07-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadMonitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadrecord",
            name="disease_type",
            field=models.IntegerField(
                choices=[
                    (0, "无"),
                    (1, "纵向裂缝"),
                    (2, "横向裂缝"),
                    (3, "龟裂"),
                    (4, "坑洼"),
                    (5, "修补"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="roadrecord",
            name="severity",
            field=models.IntegerField(
                choices=[(0, "SAFE"), (1, "LOW"), (2, "MEDIUM"), (3, "HIGH")]
            ),
        ),
    ]
