# Generated by Django 4.2.23 on 2025-07-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadMonitor', '0002_alter_roadrecord_disease_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadrecord',
            name='file_type',
            field=models.IntegerField(choices=[(0, 'VIDEO'), (1, 'IMAGE')], default=1),
            preserve_default=False,
        ),
    ]
