# Generated by Django 5.2.4 on 2025-07-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadMonitor', '0003_repaircompletionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('weather_flow', '天气客流数据'), ('occupied_taxi', '载客出租车数据'), ('weekly_flow', '周客流量数据'), ('heatmap', '热力图数据')], max_length=20, verbose_name='数据类型')),
                ('date', models.DateField(verbose_name='数据日期')),
                ('hour', models.IntegerField(blank=True, null=True, verbose_name='小时')),
                ('time_slot', models.CharField(blank=True, max_length=20, null=True, verbose_name='时间段')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='湿度')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='风速')),
                ('precip', models.FloatField(blank=True, null=True, verbose_name='降水量')),
                ('passenger_flow', models.IntegerField(default=0, verbose_name='客流量')),
                ('occupied_taxi_count', models.IntegerField(default=0, verbose_name='载客出租车数量')),
                ('total_trips', models.IntegerField(default=0, verbose_name='总行程数')),
                ('avg_speed', models.FloatField(blank=True, null=True, verbose_name='平均速度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预处理数据',
                'verbose_name_plural': '预处理数据',
                'db_table': 'preprocessed_data',
                'indexes': [models.Index(fields=['data_type', 'date'], name='preprocesse_data_ty_d90c1a_idx'), models.Index(fields=['data_type', 'date', 'hour'], name='preprocesse_data_ty_07b113_idx')],
                'unique_together': {('data_type', 'date', 'hour')},
            },
        ),
    ]
