# Generated by Django 5.2.4 on 2025-07-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadMonitor', '0004_preprocesseddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDistanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='统计日期')),
                ('short_count', models.IntegerField(default=0, verbose_name='短途数量(<4km)')),
                ('medium_count', models.IntegerField(default=0, verbose_name='中途数量(4-8km)')),
                ('long_count', models.IntegerField(default=0, verbose_name='长途数量(>8km)')),
                ('total_count', models.IntegerField(default=0, verbose_name='总行程数')),
                ('short_ratio', models.FloatField(default=0.0, verbose_name='短途占比(%)')),
                ('medium_ratio', models.FloatField(default=0.0, verbose_name='中途占比(%)')),
                ('long_ratio', models.FloatField(default=0.0, verbose_name='长途占比(%)')),
                ('avg_short_distance', models.FloatField(blank=True, null=True, verbose_name='短途平均距离(km)')),
                ('avg_medium_distance', models.FloatField(blank=True, null=True, verbose_name='中途平均距离(km)')),
                ('avg_long_distance', models.FloatField(blank=True, null=True, verbose_name='长途平均距离(km)')),
                ('avg_total_distance', models.FloatField(blank=True, null=True, verbose_name='总平均距离(km)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '路程分析统计',
                'verbose_name_plural': '路程分析统计',
                'db_table': 'trip_distance_stat',
                'indexes': [models.Index(fields=['date'], name='trip_distan_date_f7f969_idx')],
            },
        ),
    ]
