# Generated by Django 5.2.4 on 2025-07-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadMonitor', '0005_tripdistancestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDetailStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='车牌号')),
                ('date', models.DateField(verbose_name='日期')),
                ('start_time', models.DateTimeField(verbose_name='起始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('start_lng', models.FloatField(verbose_name='起点经度')),
                ('start_lat', models.FloatField(verbose_name='起点纬度')),
                ('end_lng', models.FloatField(verbose_name='终点经度')),
                ('end_lat', models.FloatField(verbose_name='终点纬度')),
                ('distance', models.FloatField(verbose_name='行程距离(km)')),
                ('duration', models.FloatField(verbose_name='行程时长(分钟)')),
                ('avg_speed', models.FloatField(verbose_name='平均速度(km/h)')),
                ('trip_type', models.CharField(choices=[('short', '短途'), ('medium', '中途'), ('long', '长途')], max_length=10, verbose_name='路程类型')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '路程明细',
                'verbose_name_plural': '路程明细',
                'db_table': 'trip_detail_stat',
                'indexes': [models.Index(fields=['date'], name='trip_detail_date_081932_idx'), models.Index(fields=['license_plate', 'date'], name='trip_detail_license_507a92_idx'), models.Index(fields=['trip_type', 'date'], name='trip_detail_trip_ty_5d90da_idx')],
            },
        ),
    ]
