# Generated by Django 5.2.4 on 2025-07-09 06:42

import web.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfaceimage",
            name="image",
            field=web.models.EncryptedImageField(upload_to=web.models.user_face_path),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="face_image",
            field=web.models.EncryptedImageField(
                blank=True, null=True, upload_to=web.models.user_face_path
            ),
        ),
    ]
