# Generated by Django 4.2.23 on 2025-07-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_userfaceimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permission',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '维修工'), (2, '管理员')], default=0),
        ),
    ]
