# Generated by Django 5.2.4 on 2025-07-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_systemlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
