# Generated by Django 4.2.23 on 2025-07-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_trajectorypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField()),
                ('alert_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('related_data', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.userprofile')),
            ],
            options={
                'db_table': 'web_alertevent',
            },
        ),
    ]
