# Generated by Django 4.2.23 on 2025-07-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alertevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='alert_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.alertevent'),
        ),
    ]
