# Generated by Django 4.2.23 on 2025-07-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
