# Generated by Django 5.2.4 on 2025-07-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_alter_useravatar_file_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemlog",
            name="alert_event",
        ),
    ]
